services:
  react:
    container_name: react
    build: .
    image: fullstack/frontend
    volumes:
      - react-volume:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./nginx
    image: fullstack/nginx
    networks:
      - fullstack-network
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - react

networks:
  fullstack-network:
    name: fullstack-network
    external: true

volumes:
  react-volume:
