on:
  push:
    branches:
      - master
name: Build and Deploy Front-end on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create an env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_REACT_APP_BACK_END_URL: ${{secrets.REACT_APP_API_BASE_URL}}
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose stop && docker compose up -d